// <auto-generated />
using System;
using ACG_Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACG_Api.Migrations
{
    [DbContext(typeof(NewDatabaseModel))]
    partial class NewDatabaseModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ACG_Class.Model.NewClass._1D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BanckAccount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edryofop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Counterparty");
                });

            modelBuilder.Entity("ACG_Class.Model.NewClass._2D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Area")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DateCloseDepartment")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_D1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pibs")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isAlert")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id_D1");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ACG_Class.Model.NewClass._2D", b =>
                {
                    b.HasOne("ACG_Class.Model.NewClass._1D", "D1")
                        .WithMany("NumberGroup")
                        .HasForeignKey("Id_D1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("D1");
                });

            modelBuilder.Entity("ACG_Class.Model.NewClass._1D", b =>
                {
                    b.Navigation("NumberGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
